# Generated by Django 5.0.4 on 2024-04-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tags18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mayores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=250)),
                ('codigo', models.TextField()),
                ('generos', models.ManyToManyField(related_name='generos18ss', to='perfil.tags18')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
