# Generated by Django 5.0.4 on 2024-04-14 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fecha_de_estreno', models.DateField()),
                ('duracion', models.PositiveBigIntegerField()),
                ('codigo_peli', models.TextField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.genero')),
            ],
        ),
    ]
