# Generated by Django 5.0.4 on 2024-04-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('subtitle', models.CharField(default='hola', max_length=100)),
                ('imagen', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fecha_de_estreno', models.DateField()),
                ('duracion', models.PositiveBigIntegerField()),
                ('codigo_peli', models.TextField()),
                ('like', models.PositiveIntegerField(default=0)),
                ('dislike', models.PositiveIntegerField(default=0)),
                ('actores', models.ManyToManyField(related_name='peliculas', to='login.actor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.genero')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('portada', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_estreno_serie', models.DateField()),
                ('duracion', models.PositiveBigIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('generos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.genero')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='agregar_cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('fecha', models.DateField()),
                ('codigo_serie', models.TextField()),
                ('seriea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partesss', to='login.series')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
