# Generated by Django 5.0.4 on 2024-04-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='subtitle',
            field=models.CharField(default='hola', max_length=100),
        ),
    ]
