# Generated by Django 5.0.4 on 2024-04-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_pelicula_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
