# Generated by Django 5.0.4 on 2024-04-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_pelicula_dislike_pelicula_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-nombre']},
        ),
    ]
