# Generated by Django 5.0.4 on 2024-04-19 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_series_alter_pelicula_options_agregar_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregar_cap',
            name='generos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.genero'),
        ),
    ]
