# Generated by Django 5.0.4 on 2024-04-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_agregar_cap_generos_series_generos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(related_name='peliculas', to='login.actor'),
        ),
    ]
