# Generated by Django 5.0.4 on 2024-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posmovis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='otro', max_length=10),
        ),
    ]
