# Generated by Django 5.0.4 on 2024-04-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posmovis', '0002_alter_profile_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
