# Generated by Django 5.0.4 on 2024-04-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posmovis', '0003_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
