# Generated by Django 5.0.4 on 2024-04-14 19:38

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posmovis', '0004_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='NZ', max_length=2),
        ),
    ]
