# Generated by Django 5.0.4 on 2024-04-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posmovis', '0005_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='pro', upload_to='perfiles/'),
        ),
    ]
