# Generated by Django 5.0.4 on 2024-04-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posmovis', '0008_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(default=3),
        ),
    ]
